[base]
pid_file = "/tmp/logic.pid"
[log]
log_path = "./log.log"
log_level = "debug"
[http]
address = "tcp@localhost:6921"
[redis]
address = "localhost:6379"
password = "****"
default_db = 0
[rpc]
address = ["tcp@localhost:6923"]
