[base]
pid_file = "/tmp/comet.pid"
server_id = "1"
[log]
log_path = "./log.log"
log_level = "debug"
[websocket]
port = ":7911"
max_message_size = 512
read_buffer_size = 1024
write_buffer_size = 1024
[bucket]
size = 8
channel = 1024
room = 1024
[prc]
    [[rpc.logic_bind]]
    key = 1
    addr = "tcp@0.0.0.0:6923"
    [[rpc.comet_bind]]
    key = 1
    addr = "tcp@0.0.0.0:6912"